Issue 38679: Duplicate rows get created for samples that have same samplefile name in multiple imported skyline documents for QC
LabKey/targetedms pull request #145
Opened 2020-03-01 05:22 UTC by labkey-ankurj

2020-03-02 18:29 UTC, labkey-jeckels requested changes

2020-03-02 18:29 UTC, labkey-jeckels commented on src/org/labkey/targetedms/outliers/CUSUMOutliers.java
> +            String sampleFileString = ljOutlier.getSampleFile() + "_" + ljOutlier.getAcquiredTime();
Why are you concatenating these together? To make sure it's unique? Would it be better to use the Id value from targetedms.samplefile?

2020-03-02 18:29 UTC, labkey-jeckels commented on src/org/labkey/targetedms/outliers/CUSUMOutliers.java
> +    private Map<String, Integer> processEachOutlier(boolean groupByGuideSet, Map<String, Integer> countObj, int guideSetId, Set<String> sampleFiles, String sampleFile, String sampleFileString)
These arguments need some additional explanation. How do sampleFile and sampleFileString relate. Part of my confusion is that they're both of type String.

2020-03-02 18:29 UTC, labkey-jeckels commented on api-src/org/labkey/api/targetedms/model/SampleFileInfo.java
> +    public int getSampleFileId()
It looks like this got added but not used. See other comment about potentially using it instead of concatenating two other columns

2020-03-03 00:58 UTC, labkey-jeckels requested changes
Code looks good. Let's take this for 20.3. Can you update the PR to point to that branch?

2020-03-03 01:01 UTC, labkey-ankurj commented
I thought the tests will restart on 20.3-SNAPSHOT on teamcity after changing the base, but they didn't. Manually kicking them off before merging.

2020-03-03 01:01 UTC, labkey-jeckels approved these changes

2020-03-03 01:10 UTC, merged