Issue 40659: Security fixes for vulnerabilities found in security scan report
LabKey/targetedms pull request #209
Opened 2020-06-18 01:19 UTC by labkey-ankurj

#### Rationale
This PR updates the jQuery version used in targetedms module.

#### Related Pull Requests
https://github.com/LabKey/platform/pull/1317

2020-06-18 22:29 UTC, labkey-jeckels approved these changes
This file doesn't appear to be used, so safe to delete. May still need followup changes to make sure spectrum viewer and the precursor resolution pages keep working when the core flips to 3.5.x

2020-06-19 19:19 UTC, labkey-jeckels requested changes
How does the code know to use the new file name? And do we need a separate copy of these files - could we reference the ones in the platform repo?

2020-06-22 18:21 UTC, labkey-ankurj commented
> How does the code know to use the new file name? And do we need a separate copy of these files - could we reference the ones in the platform repo?

Right, jQuery is not being used.

2020-06-22 18:28 UTC, labkey-jeckels approved these changes

2020-06-22 18:29 UTC, merged