Issue 44765: Increase CacheFormatVersion to 15
LabKey/targetedms pull request #485
Opened 2022-01-28 18:22 UTC by vagisha

#### Rationale
The current supported CacheFormatVersion in the targetedms module is 14. Skyline now supports version 15. The only new information added to version 15 is the "Import Time" which is the time the chromatograms were extracted. This can be ignored by Panorama so we can bump up the supported CacheFormatVersion to 15.

2022-01-28 18:39 UTC, labkey-jeckels requested changes
It feels like we should update CachedFileHeaderStruct to match. Even if we don't read the new time info, shouldn't we update getStructSize() so that we don't grab other data from the wrong offsets?

2022-01-28 19:39 UTC, vagisha commented
> It feels like we should update CachedFileHeaderStruct to match. Even if we don't read the new time info, shouldn't we update getStructSize() so that we don't grab other data from the wrong offsets?

Done.

2022-01-28 20:51 UTC, nickshulman approved these changes
Looks good to me.

2022-01-29 00:07 UTC, labkey-jeckels approved these changes

2022-01-31 21:20 UTC, merged