Item 9548 - Show peak area or quality info in protein sequence view
LabKey/targetedms pull request #531
Opened 2022-05-10 01:19 UTC by ankurjuneja

#### Rationale

#### Related Pull Requests
* 

#### Changes
*

2022-05-16 16:35 UTC, labkey-jeckels requested changes

2022-05-16 16:35 UTC, labkey-jeckels commented on src/org/labkey/targetedms/TargetedMSController.java
> +            String viewBy = getViewContext().getActionURL().getParameter("viewBy");
Suggest adding this to the form object instead of pulling it separately from the URL. May want to introduce a ChromatogramForm subclass

2022-05-16 16:35 UTC, labkey-jeckels commented on src/org/labkey/targetedms/TargetedMSController.java
> +                peptideCharacteristic.setIntensityView(group.getViewBy() != null && group.getViewBy().equalsIgnoreCase("intensity"));
Similar to my comment in the related PR, this doesn't feel like it should be a peptideCharacteristic level setting. They're all going to have the same value

2022-05-16 16:35 UTC, labkey-jeckels commented on src/org/labkey/targetedms/parser/PeptideGroup.java
> +    private String _viewBy;
This feels wrong - it's not something that we're persisting in the DB so it seems odd to add to the class that matches with the DB table

2022-05-16 16:35 UTC, labkey-jeckels commented on src/org/labkey/targetedms/query/PeptideManager.java
> +        SQLFragment sql = new SQLFragment("SELECT X.Sequence, LOG10(MAX(X.Intensity)) AS Intensity, -ROUND(LOG10(MAX(X.Confidence)),4) AS Confidence FROM ");
I think we want the raw qvalue for the confidence, not its log.

2022-05-16 16:35 UTC, labkey-jeckels commented on src/org/labkey/targetedms/query/PeptideManager.java
> +    public static PeptideCharacteristic getPeptideCharacteristic(long peptideId)
We could easily get all of the peptides for a peptideGroup in a single query.

2022-05-17 05:07 UTC, ankurjuneja commented on src/org/labkey/targetedms/query/PeptideManager.java
> +        SQLFragment sql = new SQLFragment("SELECT X.Sequence, LOG10(MAX(X.Intensity)) AS Intensity, -ROUND(LOG10(MAX(X.Confidence)),4) AS Confidence FROM ");
I followed the specs, changing to raw value

2022-05-17 05:07 UTC, ankurjuneja commented on src/org/labkey/targetedms/parser/PeptideGroup.java
> +    private String _viewBy;
yeah makes sense, I don't think it is needed anymore. removed.

2022-05-17 05:07 UTC, ankurjuneja commented on src/org/labkey/targetedms/TargetedMSController.java
> +                peptideCharacteristic.setIntensityView(group.getViewBy() != null && group.getViewBy().equalsIgnoreCase("intensity"));
yep removed it.

2022-05-17 05:07 UTC, ankurjuneja commented on src/org/labkey/targetedms/TargetedMSController.java
> +            String viewBy = getViewContext().getActionURL().getParameter("viewBy");
don't need it. removed it.

2022-05-17 05:08 UTC, ankurjuneja commented on src/org/labkey/targetedms/query/PeptideManager.java
> +    public static PeptideCharacteristic getPeptideCharacteristic(long peptideId)
yep, done

2022-05-17 14:06 UTC, labkey-jeckels commented on src/org/labkey/targetedms/query/PeptideManager.java
> +        SQLFragment sql = new SQLFragment("SELECT X.Sequence, LOG10(MAX(X.Intensity)) AS Intensity, -ROUND(LOG10(MAX(X.Confidence)),4) AS Confidence FROM ");
See comment in spec. OK to merge as-is and we can restore the log if I've misremembered.

2022-05-17 14:07 UTC, labkey-jeckels approved these changes

2022-06-02 15:01 UTC, merged