Migrate inline javascript event handlers
LabKey/targetedms pull request #873
Opened 2024-03-24 15:02 UTC by ankurjuneja

#### Rationale
A strict (no 'unsafe-inline' directive) CSP forbids all inline events. Instead, events must be attached via JavaScript inside a properly nonced script tag

#### Changes
*  PlotTypeCheckCombo.js
* protein.js
* calibrationCurve.jsp (2 onchange handlers)
* chromatogramsForm.jsp (4 onclick handlers)
* figuresOfMerit.jsp (1 onclick handler)
* pharmacokinetics.jsp (2 onclick handlers)

2024-03-27 16:02 UTC, labkey-jeckels requested changes
org.labkey.test.tests.targetedms.TargetedMSCalibrationCurveTest.testCalibrationPK appears to be failing in the branch but passing in develop

2024-03-27 18:31 UTC, ankurjuneja commented
the TC is clear now

2024-03-27 18:43 UTC, labkey-jeckels approved these changes

2024-03-27 18:43 UTC, labkey-jeckels commented on src/org/labkey/targetedms/view/pharmacokinetics.jsp
> +            <%=iconLink("fa fa-file-excel-o", "", null).onClick("exportExcel('" + h(subgroup) + "')") %>
I suspect we don't need the `h()` call here. I hope `onClick()` already does the appropriate encoding for us.

2024-03-27 18:43 UTC, labkey-jeckels commented on src/org/labkey/targetedms/view/pharmacokinetics.jsp
> +                <% addHandler("btnNonIVC0-"+h(subgroup), "click", "updateStatsForNonIVC0('"+ h(subgroup) + "')"); %>
Similar here - probably don't need the call to `h()` or we'll get double-encoding

2024-03-28 00:02 UTC, merged

2024-03-29 21:32 UTC, labkey-adam commented
@ankurjuneja looks like the `figuresOfMerit.jsp` change didn't make it into this PR