Teamcity intermittent test failures
LabKey/targetedms pull request #947
Opened 2024-08-14 09:43 UTC by labkey-sweta

#### Rationale
Fixing two intermittent test failures 

1. TargetedMSUtilizationCalendarTest.testUtilizationCalendarActions
2. TargetedMSSampleManagerIntegrationTest

#### Related Pull Requests
* 

#### Changes
*

2024-08-14 17:22 UTC, labkey-tchad requested changes

2024-08-14 17:22 UTC, labkey-tchad commented on test/src/org/labkey/test/components/targetedms/UtilizationCalendarWebPart.java
> +        doAndWaitForElementToRefresh(() -> modalDialog.dismiss("Save", 0), elementCache().dayLoc.withText(extractDay(startDate)), 10);
FYI, none of the calls to `modalDialog.dismiss` in this class actually wait for the dialog to go away. Making them do so might improve its general reliability.

```suggestion
        doAndWaitForElementToRefresh(() -> modalDialog.dismiss("Save"), elementCache().dayLoc.withText(extractDay(startDate)), 10);
```

2024-08-14 17:22 UTC, labkey-tchad commented on test/src/org/labkey/test/tests/panoramapremium/TargetedMSSampleManagerIntegrationTest.java
> +        SampleTypeAPIHelper.createEmptySampleType(getProjectName(), new SampleTypeDefinition(sampleName));
This doesn't look like it's creating the sample type in the correct location
```suggestion
        SampleTypeAPIHelper.createEmptySampleType(getProjectName() + Sample_Manager_Subfolder, new SampleTypeDefinition(sampleName));
```

2024-08-15 15:26 UTC, labkey-danield approved these changes

2024-08-15 15:42 UTC, labkey-danield requested changes
The pathway used to create the sample type is not correct.
Please have a successful run on TeamCity before asking for a code review.

2024-08-16 15:16 UTC, labkey-tchad approved these changes

2024-08-16 15:22 UTC, labkey-tchad commented on test/src/org/labkey/test/components/targetedms/UtilizationCalendarWebPart.java
> +        doAndWaitForElementToRefresh(() -> modalDialog.dismiss("Save"), elementCache().dayLoc.withText(extractDay(startDate)), 10);
With the change in testAutomation, you should be able to remove the `, 0` from all of the calls to `modalDialog.dismiss`

2024-08-16 16:44 UTC, labkey-danield approved these changes

2024-08-18 16:51 UTC, merged